import type { TarotCard } from "@/types/tarot";

// ============================================
// Major Arcana (22 cards)
// ============================================

const majorArcana: TarotCard[] = [
  {
    id: "the-fool",
    name: "The Fool",
    arcana: "major",
    number: 0,
    image: "https://upload.wikimedia.org/wikipedia/commons/9/90/RWS_Tarot_00_Fool.jpg",
    description: "The Fool represents new beginnings, innocence, and spontaneity. This card encourages you to take a leap of faith.",
    keywords: ["new beginnings", "innocence", "spontaneity", "free spirit", "adventure"],
    uprightMeaning: "New beginnings, innocence, spontaneity, a free spirit. The Fool encourages you to embrace the unknown with an open heart.",
    reversedMeaning: "Recklessness, risk-taking, foolishness. You may be acting without thinking or ignoring potential consequences.",
    loveMeaning: "A new romantic adventure or fresh start in love. Embrace spontaneity in your relationships.",
    careerMeaning: "A new career path or exciting opportunity. Take the leap of faith in your professional life.",
    financeMeaning: "Be cautious with impulsive spending. New financial opportunities may arise unexpectedly.",
    healthMeaning: "A fresh start in health habits. Embrace new wellness routines with enthusiasm.",
    element: "Air",
    planet: "Uranus",
    astrology: "Aquarius",
    numerology: "0 - Unlimited potential",
  },
  {
    id: "the-magician",
    name: "The Magician",
    arcana: "major",
    number: 1,
    image: "https://upload.wikimedia.org/wikipedia/commons/d/de/RWS_Tarot_01_Magician.jpg",
    description: "The Magician represents manifestation, resourcefulness, and power. You have all the tools you need.",
    keywords: ["manifestation", "resourcefulness", "power", "inspired action", "willpower"],
    uprightMeaning: "Manifestation, resourcefulness, power, inspired action. You have all the tools to manifest your desires.",
    reversedMeaning: "Manipulation, poor planning, untapped talents. You may not be using your full potential.",
    loveMeaning: "Taking action in love. Use your charm and confidence to attract or strengthen relationships.",
    careerMeaning: "Skill mastery and professional growth. You have the talent to succeed in your career goals.",
    financeMeaning: "Financial manifestation and smart money management. Use your resources wisely.",
    healthMeaning: "Taking control of your health. You have the power to make positive changes.",
    element: "Air",
    planet: "Mercury",
    astrology: "Gemini/Virgo",
    numerology: "1 - New beginnings, creation",
  },
  {
    id: "the-high-priestess",
    name: "The High Priestess",
    arcana: "major",
    number: 2,
    image: "https://upload.wikimedia.org/wikipedia/commons/8/88/RWS_Tarot_02_High_Priestess.jpg",
    description: "The High Priestess represents intuition, sacred knowledge, and the subconscious mind.",
    keywords: ["intuition", "sacred knowledge", "subconscious", "mystery", "inner voice"],
    uprightMeaning: "Intuition, sacred knowledge, divine feminine, the subconscious mind. Trust your inner voice.",
    reversedMeaning: "Secrets, disconnected from intuition, withdrawal. You may be ignoring your inner guidance.",
    loveMeaning: "Trust your intuition about your partner. Hidden emotions may need to be explored.",
    careerMeaning: "Use intuition in career decisions. Hidden knowledge may be revealed soon.",
    financeMeaning: "Trust your gut feelings about financial decisions. Not all information is visible yet.",
    healthMeaning: "Listen to your body's signals. Pay attention to subtle health messages.",
    element: "Water",
    planet: "Moon",
    astrology: "Cancer",
    numerology: "2 - Balance, duality",
  },
  {
    id: "the-empress",
    name: "The Empress",
    arcana: "major",
    number: 3,
    image: "https://upload.wikimedia.org/wikipedia/commons/d/d2/RWS_Tarot_03_Empress.jpg",
    description: "The Empress represents femininity, beauty, nature, and abundance.",
    keywords: ["femininity", "beauty", "nature", "abundance", "nurturing"],
    uprightMeaning: "Femininity, beauty, nature, nurturing, abundance. A period of growth and creativity.",
    reversedMeaning: "Creative block, dependence on others, smothering. You may be neglecting self-care.",
    loveMeaning: "Deep love, fertility, and emotional abundance. A nurturing phase in relationships.",
    careerMeaning: "Creative projects flourish. A period of professional abundance and growth.",
    financeMeaning: "Financial abundance and prosperity. Investments in creativity pay off.",
    healthMeaning: "Excellent health and vitality. Focus on nurturing your body and mind.",
    element: "Earth",
    planet: "Venus",
    astrology: "Taurus/Libra",
    numerology: "3 - Creativity, expression",
  },
  {
    id: "the-emperor",
    name: "The Emperor",
    arcana: "major",
    number: 4,
    image: "https://upload.wikimedia.org/wikipedia/commons/c/c3/RWS_Tarot_04_Emperor.jpg",
    description: "The Emperor represents authority, structure, and paternal influence.",
    keywords: ["authority", "structure", "control", "father figure", "stability"],
    uprightMeaning: "Authority, establishment, structure, a father figure. Stability and control in your life.",
    reversedMeaning: "Domination, excessive control, rigidity. You may be too controlling or inflexible.",
    loveMeaning: "Stability and commitment in love. A protective and loyal partner.",
    careerMeaning: "Leadership and authority. Taking charge of your professional life.",
    financeMeaning: "Financial stability through discipline and structure. Strong foundations.",
    healthMeaning: "Structured approach to health. Discipline in wellness routines pays off.",
    element: "Fire",
    planet: "Mars",
    astrology: "Aries",
    numerology: "4 - Stability, foundation",
  },
  {
    id: "the-hierophant",
    name: "The Hierophant",
    arcana: "major",
    number: 5,
    image: "https://upload.wikimedia.org/wikipedia/commons/8/8d/RWS_Tarot_05_Hierophant.jpg",
    description: "The Hierophant represents spiritual wisdom, religious beliefs, and tradition.",
    keywords: ["spiritual wisdom", "tradition", "conformity", "morality", "education"],
    uprightMeaning: "Spiritual wisdom, religious beliefs, conformity, tradition, institutions.",
    reversedMeaning: "Personal beliefs, freedom, challenging the status quo. Breaking from tradition.",
    loveMeaning: "Traditional values in relationships. Commitment and conventional partnerships.",
    careerMeaning: "Mentorship and institutional learning. Following established career paths.",
    financeMeaning: "Conservative financial strategies. Following proven money management methods.",
    healthMeaning: "Traditional medicine and established health practices. Seek expert guidance.",
    element: "Earth",
    planet: "Venus",
    astrology: "Taurus",
    numerology: "5 - Change, freedom",
  },
  {
    id: "the-lovers",
    name: "The Lovers",
    arcana: "major",
    number: 6,
    image: "https://upload.wikimedia.org/wikipedia/commons/d/db/RWS_Tarot_06_Lovers.jpg",
    description: "The Lovers represents love, harmony, relationships, and values alignment.",
    keywords: ["love", "harmony", "relationships", "values", "choices"],
    uprightMeaning: "Love, harmony, relationships, values alignment, choices. A deep soul connection.",
    reversedMeaning: "Self-love, disharmony, imbalance, misalignment of values.",
    loveMeaning: "Deep romantic connection and soulmate energy. Important relationship decisions.",
    careerMeaning: "Professional partnerships and alignment with your values in career choices.",
    financeMeaning: "Financial decisions that align with your values. Joint financial ventures.",
    healthMeaning: "Mind-body harmony. Balance between physical and emotional well-being.",
    element: "Air",
    planet: "Mercury",
    astrology: "Gemini",
    numerology: "6 - Harmony, balance",
  },
  {
    id: "the-chariot",
    name: "The Chariot",
    arcana: "major",
    number: 7,
    image: "https://upload.wikimedia.org/wikipedia/commons/9/9b/RWS_Tarot_07_Chariot.jpg",
    description: "The Chariot represents determination, willpower, and triumph through effort.",
    keywords: ["determination", "willpower", "triumph", "control", "direction"],
    uprightMeaning: "Determination, willpower, control, success, ambition. Victory through focused effort.",
    reversedMeaning: "Self-discipline, opposition, lack of direction. Feeling out of control.",
    loveMeaning: "Moving forward in love with determination. Overcoming relationship obstacles.",
    careerMeaning: "Career advancement through sheer willpower. Determined pursuit of goals.",
    financeMeaning: "Financial progress through discipline. Overcoming monetary obstacles.",
    healthMeaning: "Strong determination in health goals. Overcoming health challenges with willpower.",
    element: "Water",
    planet: "Moon",
    astrology: "Cancer",
    numerology: "7 - Spiritual growth, reflection",
  },
  {
    id: "strength",
    name: "Strength",
    arcana: "major",
    number: 8,
    image: "https://upload.wikimedia.org/wikipedia/commons/f/f5/RWS_Tarot_08_Strength.jpg",
    description: "Strength represents courage, inner strength, and compassionate control.",
    keywords: ["courage", "inner strength", "compassion", "patience", "influence"],
    uprightMeaning: "Strength, courage, persuasion, influence, compassion. Inner power and gentle control.",
    reversedMeaning: "Inner strength waning, self-doubt, raw emotion. Feeling powerless.",
    loveMeaning: "Gentle strength in relationships. Compassion and patience with your partner.",
    careerMeaning: "Quiet confidence at work. Leading through influence rather than force.",
    financeMeaning: "Patient approach to financial growth. Inner strength in money management.",
    healthMeaning: "Inner resilience and healing. Gentle approach to health improvement.",
    element: "Fire",
    planet: "Sun",
    astrology: "Leo",
    numerology: "8 - Power, abundance",
  },
  {
    id: "the-hermit",
    name: "The Hermit",
    arcana: "major",
    number: 9,
    image: "https://upload.wikimedia.org/wikipedia/commons/4/4d/RWS_Tarot_09_Hermit.jpg",
    description: "The Hermit represents soul searching, introspection, and inner guidance.",
    keywords: ["soul searching", "introspection", "solitude", "inner guidance", "wisdom"],
    uprightMeaning: "Soul searching, introspection, being alone, inner guidance. A period of reflection.",
    reversedMeaning: "Isolation, loneliness, withdrawal. Too much solitude can be harmful.",
    loveMeaning: "Time for self-reflection in love. Understanding what you truly want in a partner.",
    careerMeaning: "Career contemplation and soul searching. Finding your true professional calling.",
    financeMeaning: "Careful financial contemplation. Taking time to plan your financial future.",
    healthMeaning: "Mental health awareness. Taking time for solitude and healing.",
    element: "Earth",
    planet: "Mercury",
    astrology: "Virgo",
    numerology: "9 - Completion, wisdom",
  },
  {
    id: "wheel-of-fortune",
    name: "Wheel of Fortune",
    arcana: "major",
    number: 10,
    image: "https://upload.wikimedia.org/wikipedia/commons/3/3c/RWS_Tarot_10_Wheel_of_Fortune.jpg",
    description: "The Wheel of Fortune represents good luck, karma, cycles, and destiny.",
    keywords: ["good luck", "karma", "destiny", "turning point", "cycles"],
    uprightMeaning: "Good luck, karma, life cycles, destiny, a turning point. Fortune favors you.",
    reversedMeaning: "Bad luck, resistance to change, breaking cycles. Feeling stuck.",
    loveMeaning: "Destined romantic encounters. A turning point in your love life.",
    careerMeaning: "Lucky career opportunities. A major professional turning point.",
    financeMeaning: "Financial luck and fortune. Cycles of abundance are turning in your favor.",
    healthMeaning: "Health cycles improving. A positive turning point in wellness.",
    element: "Fire",
    planet: "Jupiter",
    astrology: "Sagittarius",
    numerology: "10 - Completion, new cycle",
  },
  {
    id: "justice",
    name: "Justice",
    arcana: "major",
    number: 11,
    image: "https://upload.wikimedia.org/wikipedia/commons/e/e0/RWS_Tarot_11_Justice.jpg",
    description: "Justice represents fairness, truth, cause and effect, and law.",
    keywords: ["fairness", "truth", "law", "cause and effect", "clarity"],
    uprightMeaning: "Justice, fairness, truth, cause and effect. Legal matters resolved fairly.",
    reversedMeaning: "Unfairness, lack of accountability, dishonesty. Injustice in your situation.",
    loveMeaning: "Fair and balanced relationships. Honest communication with your partner.",
    careerMeaning: "Fair outcomes in career matters. Legal or ethical issues resolved justly.",
    financeMeaning: "Fair financial dealings. Legal financial matters resolved in your favor.",
    healthMeaning: "Balance in health. Cause and effect of health choices becoming clear.",
    element: "Air",
    planet: "Venus",
    astrology: "Libra",
    numerology: "11 - Master number, spiritual insight",
  },
  {
    id: "the-hanged-man",
    name: "The Hanged Man",
    arcana: "major",
    number: 12,
    image: "https://upload.wikimedia.org/wikipedia/commons/2/2b/RWS_Tarot_12_Hanged_Man.jpg",
    description: "The Hanged Man represents surrender, new perspectives, and letting go.",
    keywords: ["surrender", "new perspective", "letting go", "pause", "sacrifice"],
    uprightMeaning: "Pause, surrender, letting go, new perspectives. See things from a different angle.",
    reversedMeaning: "Delays, resistance, stalling, indecision. Unwillingness to make a sacrifice.",
    loveMeaning: "Seeing your relationship from a new perspective. Letting go of expectations.",
    careerMeaning: "Career pause for reflection. Gaining new professional perspectives.",
    financeMeaning: "Financial pause. Reconsidering your money priorities and values.",
    healthMeaning: "Pause in health routines for reassessment. New healing perspectives.",
    element: "Water",
    planet: "Neptune",
    astrology: "Pisces",
    numerology: "12 - Sacrifice, release",
  },
  {
    id: "death",
    name: "Death",
    arcana: "major",
    number: 13,
    image: "https://upload.wikimedia.org/wikipedia/commons/d/d7/RWS_Tarot_13_Death.jpg",
    description: "Death represents endings, change, transformation, and transition.",
    keywords: ["endings", "change", "transformation", "transition", "rebirth"],
    uprightMeaning: "Endings, change, transformation, transition. Something must end for new things to begin.",
    reversedMeaning: "Resistance to change, personal transformation, inner purging.",
    loveMeaning: "End of a relationship phase and beginning of a new one. Transformation in love.",
    careerMeaning: "Career transformation. End of one professional chapter, beginning of another.",
    financeMeaning: "Financial transformation. Ending old money habits for new prosperity.",
    healthMeaning: "Health transformation. Ending unhealthy habits for a fresh start.",
    element: "Water",
    planet: "Pluto",
    astrology: "Scorpio",
    numerology: "13 - Transformation, rebirth",
  },
  {
    id: "temperance",
    name: "Temperance",
    arcana: "major",
    number: 14,
    image: "https://upload.wikimedia.org/wikipedia/commons/f/f8/RWS_Tarot_14_Temperance.jpg",
    description: "Temperance represents balance, moderation, patience, and purpose.",
    keywords: ["balance", "moderation", "patience", "purpose", "meaning"],
    uprightMeaning: "Balance, moderation, patience, purpose. Finding the middle ground.",
    reversedMeaning: "Imbalance, excess, self-healing, realignment. Overindulgence in some area.",
    loveMeaning: "Balanced and harmonious relationships. Patience and understanding in love.",
    careerMeaning: "Work-life balance. Patient approach to career growth yields results.",
    financeMeaning: "Moderate spending and balanced finances. Patient financial planning.",
    healthMeaning: "Balanced health approach. Moderation in diet and exercise.",
    element: "Fire",
    planet: "Jupiter",
    astrology: "Sagittarius",
    numerology: "14 - Balance, temperance",
  },
  {
    id: "the-devil",
    name: "The Devil",
    arcana: "major",
    number: 15,
    image: "https://upload.wikimedia.org/wikipedia/commons/5/55/RWS_Tarot_15_Devil.jpg",
    description: "The Devil represents shadow self, attachment, addiction, and restriction.",
    keywords: ["shadow self", "attachment", "addiction", "restriction", "materialism"],
    uprightMeaning: "Shadow self, attachment, addiction, restriction, sexuality. Breaking free from bonds.",
    reversedMeaning: "Releasing limiting beliefs, exploring dark thoughts, detachment.",
    loveMeaning: "Unhealthy attachments or passionate intensity. Examine relationship patterns.",
    careerMeaning: "Feeling trapped in your career. Breaking free from professional restrictions.",
    financeMeaning: "Material obsession. Breaking free from unhealthy financial patterns.",
    healthMeaning: "Addressing addictions and unhealthy habits. Shadow work in healing.",
    element: "Earth",
    planet: "Saturn",
    astrology: "Capricorn",
    numerology: "15 - Shadow, temptation",
  },
  {
    id: "the-tower",
    name: "The Tower",
    arcana: "major",
    number: 16,
    image: "https://upload.wikimedia.org/wikipedia/commons/5/53/RWS_Tarot_16_Tower.jpg",
    description: "The Tower represents sudden change, upheaval, revelation, and awakening.",
    keywords: ["sudden change", "upheaval", "revelation", "awakening", "chaos"],
    uprightMeaning: "Sudden change, upheaval, chaos, revelation, awakening. Necessary destruction for rebuilding.",
    reversedMeaning: "Personal transformation, fear of change, averting disaster.",
    loveMeaning: "Sudden relationship changes. Revelations that shake the foundation of love.",
    careerMeaning: "Sudden career upheaval. Unexpected professional changes lead to growth.",
    financeMeaning: "Financial upheaval. Unexpected monetary changes require adaptation.",
    healthMeaning: "Sudden health wake-up call. Necessary changes in health approach.",
    element: "Fire",
    planet: "Mars",
    astrology: "Aries/Scorpio",
    numerology: "16 - Sudden change, awakening",
  },
  {
    id: "the-star",
    name: "The Star",
    arcana: "major",
    number: 17,
    image: "https://upload.wikimedia.org/wikipedia/commons/d/db/RWS_Tarot_17_Star.jpg",
    description: "The Star represents hope, faith, purpose, renewal, and spirituality.",
    keywords: ["hope", "faith", "renewal", "spirituality", "serenity"],
    uprightMeaning: "Hope, faith, purpose, renewal, spirituality. A time of healing and inspiration.",
    reversedMeaning: "Lack of faith, despair, self-trust, disconnection. Losing hope.",
    loveMeaning: "Renewed hope in love. A period of healing and spiritual connection.",
    careerMeaning: "Career inspiration and renewed purpose. Aligning work with your calling.",
    financeMeaning: "Financial hope and renewal. Trusting in abundance and prosperity.",
    healthMeaning: "Healing and renewal. A period of excellent health and spiritual wellness.",
    element: "Air",
    planet: "Uranus",
    astrology: "Aquarius",
    numerology: "17 - Hope, inspiration",
  },
  {
    id: "the-moon",
    name: "The Moon",
    arcana: "major",
    number: 18,
    image: "https://upload.wikimedia.org/wikipedia/commons/7/7f/RWS_Tarot_18_Moon.jpg",
    description: "The Moon represents illusion, fear, anxiety, subconscious, and intuition.",
    keywords: ["illusion", "fear", "anxiety", "subconscious", "intuition"],
    uprightMeaning: "Illusion, fear, anxiety, subconscious, intuition. Things are not as they seem.",
    reversedMeaning: "Release of fear, repressed emotion, inner confusion clearing.",
    loveMeaning: "Uncertainty in love. Trust your intuition about hidden relationship dynamics.",
    careerMeaning: "Career confusion or hidden workplace dynamics. Trust your instincts.",
    financeMeaning: "Financial uncertainty. Hidden financial information may be revealed.",
    healthMeaning: "Anxiety and emotional health concerns. Pay attention to subconscious signals.",
    element: "Water",
    planet: "Neptune",
    astrology: "Pisces",
    numerology: "18 - Illusion, intuition",
  },
  {
    id: "the-sun",
    name: "The Sun",
    arcana: "major",
    number: 19,
    image: "https://upload.wikimedia.org/wikipedia/commons/1/17/RWS_Tarot_19_Sun.jpg",
    description: "The Sun represents positivity, fun, warmth, success, and vitality.",
    keywords: ["positivity", "fun", "warmth", "success", "vitality"],
    uprightMeaning: "Positivity, fun, warmth, success, vitality. Joy and accomplishment shine on you.",
    reversedMeaning: "Inner child wounded, overly optimistic, temporary depression.",
    loveMeaning: "Joyful and warm love. Positivity and happiness in relationships.",
    careerMeaning: "Career success and recognition. A bright and positive professional period.",
    financeMeaning: "Financial success and abundance. Warm and positive money energy.",
    healthMeaning: "Excellent vitality and health. Energy and positivity in wellness.",
    element: "Fire",
    planet: "Sun",
    astrology: "Leo",
    numerology: "19 - Success, joy",
  },
  {
    id: "judgement",
    name: "Judgement",
    arcana: "major",
    number: 20,
    image: "https://upload.wikimedia.org/wikipedia/commons/d/dd/RWS_Tarot_20_Judgement.jpg",
    description: "Judgement represents reflection, reckoning, awakening, and inner calling.",
    keywords: ["reflection", "reckoning", "awakening", "inner calling", "absolution"],
    uprightMeaning: "Judgement, rebirth, inner calling, absolution. Answering your higher purpose.",
    reversedMeaning: "Self-doubt, inner critic, ignoring the call. Fear of judgement.",
    loveMeaning: "Evaluating your love life. Making important relationship decisions.",
    careerMeaning: "Career reckoning and evaluation. Answering your true professional calling.",
    financeMeaning: "Financial reckoning. Evaluating and correcting past financial decisions.",
    healthMeaning: "Health evaluation and awakening. Answering the call to improve wellness.",
    element: "Fire",
    planet: "Pluto",
    astrology: "Scorpio",
    numerology: "20 - Judgement, renewal",
  },
  {
    id: "the-world",
    name: "The World",
    arcana: "major",
    number: 21,
    image: "https://upload.wikimedia.org/wikipedia/commons/f/ff/RWS_Tarot_21_World.jpg",
    description: "The World represents completion, integration, accomplishment, and travel.",
    keywords: ["completion", "integration", "accomplishment", "travel", "fulfillment"],
    uprightMeaning: "Completion, integration, accomplishment, travel. You have achieved a major life milestone.",
    reversedMeaning: "Seeking personal closure, short-cuts, delays. Feeling incomplete.",
    loveMeaning: "Fulfillment in love. A complete and harmonious relationship.",
    careerMeaning: "Career accomplishment and completion. Reaching a major professional goal.",
    financeMeaning: "Financial fulfillment and completion. Achieving monetary goals.",
    healthMeaning: "Complete wellness and health fulfillment. A holistic approach pays off.",
    element: "Earth",
    planet: "Saturn",
    astrology: "Capricorn/Aquarius",
    numerology: "21 - Completion, wholeness",
  },
];

// ============================================
// Minor Arcana Helper
// ============================================


const minorUrls: Record<string, string> = {
  "wands-1": "https://upload.wikimedia.org/wikipedia/commons/1/11/Wands01.jpg",
  "wands-2": "https://upload.wikimedia.org/wikipedia/commons/0/0f/Wands02.jpg",
  "wands-3": "https://upload.wikimedia.org/wikipedia/commons/f/ff/Wands03.jpg",
  "wands-4": "https://upload.wikimedia.org/wikipedia/commons/a/a4/Wands04.jpg",
  "wands-5": "https://upload.wikimedia.org/wikipedia/commons/9/9d/Wands05.jpg",
  "wands-6": "https://upload.wikimedia.org/wikipedia/commons/3/3b/Wands06.jpg",
  "wands-7": "https://upload.wikimedia.org/wikipedia/commons/e/e4/Wands07.jpg",
  "wands-8": "https://upload.wikimedia.org/wikipedia/commons/6/6b/Wands08.jpg",
  "wands-9": "https://upload.wikimedia.org/wikipedia/commons/e/e7/Wands09.jpg",
  "wands-10": "https://upload.wikimedia.org/wikipedia/commons/0/0b/Wands10.jpg",
  "wands-11": "https://upload.wikimedia.org/wikipedia/commons/6/6a/Wands11.jpg",
  "wands-12": "https://upload.wikimedia.org/wikipedia/commons/1/16/Wands12.jpg",
  "wands-13": "https://upload.wikimedia.org/wikipedia/commons/0/0d/Wands13.jpg",
  "wands-14": "https://upload.wikimedia.org/wikipedia/commons/c/ce/Wands14.jpg",
  "cups-1": "https://upload.wikimedia.org/wikipedia/commons/3/36/Cups01.jpg",
  "cups-2": "https://upload.wikimedia.org/wikipedia/commons/f/f8/Cups02.jpg",
  "cups-3": "https://upload.wikimedia.org/wikipedia/commons/7/7a/Cups03.jpg",
  "cups-4": "https://upload.wikimedia.org/wikipedia/commons/3/35/Cups04.jpg",
  "cups-5": "https://upload.wikimedia.org/wikipedia/commons/d/d7/Cups05.jpg",
  "cups-6": "https://upload.wikimedia.org/wikipedia/commons/1/17/Cups06.jpg",
  "cups-7": "https://upload.wikimedia.org/wikipedia/commons/a/ae/Cups07.jpg",
  "cups-8": "https://upload.wikimedia.org/wikipedia/commons/6/60/Cups08.jpg",
  "cups-9": "https://upload.wikimedia.org/wikipedia/commons/2/24/Cups09.jpg",
  "cups-10": "https://upload.wikimedia.org/wikipedia/commons/8/84/Cups10.jpg",
  "cups-11": "https://upload.wikimedia.org/wikipedia/commons/a/ad/Cups11.jpg",
  "cups-12": "https://upload.wikimedia.org/wikipedia/commons/f/fa/Cups12.jpg",
  "cups-13": "https://upload.wikimedia.org/wikipedia/commons/6/62/Cups13.jpg",
  "cups-14": "https://upload.wikimedia.org/wikipedia/commons/0/04/Cups14.jpg",
  "swords-1": "https://upload.wikimedia.org/wikipedia/commons/1/1a/Swords01.jpg",
  "swords-2": "https://upload.wikimedia.org/wikipedia/commons/9/9e/Swords02.jpg",
  "swords-3": "https://upload.wikimedia.org/wikipedia/commons/0/02/Swords03.jpg",
  "swords-4": "https://upload.wikimedia.org/wikipedia/commons/b/bf/Swords04.jpg",
  "swords-5": "https://upload.wikimedia.org/wikipedia/commons/2/23/Swords05.jpg",
  "swords-6": "https://upload.wikimedia.org/wikipedia/commons/2/29/Swords06.jpg",
  "swords-7": "https://upload.wikimedia.org/wikipedia/commons/3/34/Swords07.jpg",
  "swords-8": "https://upload.wikimedia.org/wikipedia/commons/a/a7/Swords08.jpg",
  "swords-9": "https://upload.wikimedia.org/wikipedia/commons/2/2f/Swords09.jpg",
  "swords-10": "https://upload.wikimedia.org/wikipedia/commons/d/d4/Swords10.jpg",
  "swords-11": "https://upload.wikimedia.org/wikipedia/commons/4/4c/Swords11.jpg",
  "swords-12": "https://upload.wikimedia.org/wikipedia/commons/b/b0/Swords12.jpg",
  "swords-13": "https://upload.wikimedia.org/wikipedia/commons/d/d4/Swords13.jpg",
  "swords-14": "https://upload.wikimedia.org/wikipedia/commons/3/33/Swords14.jpg",
  "pentacles-1": "https://upload.wikimedia.org/wikipedia/commons/f/fd/Pents01.jpg",
  "pentacles-2": "https://upload.wikimedia.org/wikipedia/commons/9/9f/Pents02.jpg",
  "pentacles-3": "https://upload.wikimedia.org/wikipedia/commons/4/42/Pents03.jpg",
  "pentacles-4": "https://upload.wikimedia.org/wikipedia/commons/3/35/Pents04.jpg",
  "pentacles-5": "https://upload.wikimedia.org/wikipedia/commons/9/96/Pents05.jpg",
  "pentacles-6": "https://upload.wikimedia.org/wikipedia/commons/a/a6/Pents06.jpg",
  "pentacles-7": "https://upload.wikimedia.org/wikipedia/commons/6/6a/Pents07.jpg",
  "pentacles-8": "https://upload.wikimedia.org/wikipedia/commons/4/49/Pents08.jpg",
  "pentacles-9": "https://upload.wikimedia.org/wikipedia/commons/f/f0/Pents09.jpg",
  "pentacles-10": "https://upload.wikimedia.org/wikipedia/commons/4/42/Pents10.jpg",
  "pentacles-11": "https://upload.wikimedia.org/wikipedia/commons/e/ec/Pents11.jpg",
  "pentacles-12": "https://upload.wikimedia.org/wikipedia/commons/d/d5/Pents12.jpg",
  "pentacles-13": "https://upload.wikimedia.org/wikipedia/commons/8/88/Pents13.jpg",
  "pentacles-14": "https://upload.wikimedia.org/wikipedia/commons/1/1c/Pents14.jpg"
};

function createMinorCard(
  suit: "wands" | "cups" | "swords" | "pentacles",
  number: number,
  name: string,
  overrides: Partial<TarotCard>
): TarotCard {
  const elements = { wands: "Fire", cups: "Water", swords: "Air", pentacles: "Earth" };
  const planets = { wands: "Mars", cups: "Venus", swords: "Mercury", pentacles: "Saturn" };

  return {
    id: `${name.toLowerCase().replace(/\s+/g, "-")}`,
    name,
    arcana: "minor",
    suit,
    number,
    image: minorUrls[`${suit}-${number}`] || `/cards/${suit}/${name.toLowerCase().replace(/\s+/g, "-")}.webp`,
    description: "",
    keywords: [],
    uprightMeaning: "",
    reversedMeaning: "",
    loveMeaning: "",
    careerMeaning: "",
    financeMeaning: "",
    healthMeaning: "",
    element: elements[suit],
    planet: planets[suit],
    astrology: "",
    numerology: `${number}`,
    ...overrides,
  };
}

// ============================================
// Minor Arcana - Wands
// ============================================

const wands: TarotCard[] = [
  createMinorCard("wands", 1, "Ace of Wands", {
    keywords: ["inspiration", "new opportunity", "growth", "potential"],
    description: "The Ace of Wands signals a bold new beginning, creative inspiration, and the spark of potential.",
    uprightMeaning: "Inspiration, new opportunities, growth, potential. A powerful creative spark ignites.",
    reversedMeaning: "An emerging idea not yet fully formed, delays in starting, lack of direction.",
    loveMeaning: "Passionate new romance or renewed spark in existing relationship.",
    careerMeaning: "Exciting new career opportunity or creative project beginning.",
    financeMeaning: "New financial venture or investment opportunity with great potential.",
    healthMeaning: "Burst of energy and vitality. New health initiative.",
  }),
  createMinorCard("wands", 2, "Two of Wands", {
    keywords: ["planning", "decisions", "discovery", "progress"],
    description: "The Two of Wands represents planning, making decisions, and future exploration.",
    uprightMeaning: "Future planning, progress, decisions, discovery. The world is at your fingertips.",
    reversedMeaning: "Fear of the unknown, lack of planning, playing it safe.",
    loveMeaning: "Planning your romantic future. Deciding between staying or exploring.",
    careerMeaning: "Career planning and strategic decisions. Expanding your horizons.",
    financeMeaning: "Financial planning and future investment strategies.",
    healthMeaning: "Planning health goals. Exploring new wellness approaches.",
  }),
  createMinorCard("wands", 3, "Three of Wands", {
    keywords: ["expansion", "foresight", "overseas", "growth"],
    description: "The Three of Wands represents expansion, foresight, and looking to the future.",
    uprightMeaning: "Progress, expansion, foresight, overseas opportunities. Your plans are taking shape.",
    reversedMeaning: "Obstacles to progress, delays, frustration with lack of results.",
    loveMeaning: "Relationship expanding and growing. Long-distance love possibilities.",
    careerMeaning: "Career expansion and international opportunities.",
    financeMeaning: "Financial growth and expansion. International financial opportunities.",
    healthMeaning: "Health improvements becoming visible. Progress in wellness journey.",
  }),
  createMinorCard("wands", 4, "Four of Wands", {
    keywords: ["celebration", "harmony", "homecoming", "community"],
    description: "The Four of Wands represents celebration, harmony, and community.",
    uprightMeaning: "Celebration, joy, harmony, relaxation, homecoming. A time of happiness.",
    reversedMeaning: "Personal celebration, inner harmony, transition, lack of support.",
    loveMeaning: "Celebrations in love. Engagements, weddings, or relationship milestones.",
    careerMeaning: "Professional celebrations and achievements. Harmonious work environment.",
    financeMeaning: "Financial celebration. Achieving a monetary milestone.",
    healthMeaning: "Celebrating health achievements. A harmonious period of wellness.",
  }),
  createMinorCard("wands", 5, "Five of Wands", {
    keywords: ["conflict", "competition", "tension", "diversity"],
    description: "The Five of Wands represents conflict, disagreements, and competition.",
    uprightMeaning: "Conflict, disagreements, competition, tension. Challenges test your resolve.",
    reversedMeaning: "Inner conflict, conflict avoidance, tension release.",
    loveMeaning: "Arguments or competition in love. Working through relationship conflicts.",
    careerMeaning: "Workplace competition and conflicts. Standing your ground professionally.",
    financeMeaning: "Financial competition and disputes. Defending your financial interests.",
    healthMeaning: "Stress and tension affecting health. Address conflicts for better wellness.",
  }),
  createMinorCard("wands", 6, "Six of Wands", {
    keywords: ["victory", "success", "public recognition", "progress"],
    description: "The Six of Wands represents victory, success, and public recognition.",
    uprightMeaning: "Success, public recognition, progress, self-confidence. Victory is yours.",
    reversedMeaning: "Excess pride, lack of recognition, punishment. Private achievement.",
    loveMeaning: "Success and recognition in love. Public acknowledgment of your relationship.",
    careerMeaning: "Professional victory and recognition. Career achievements celebrated.",
    financeMeaning: "Financial success and public recognition of your prosperity.",
    healthMeaning: "Health victories. Successfully overcoming health challenges.",
  }),
  createMinorCard("wands", 7, "Seven of Wands", {
    keywords: ["challenge", "perseverance", "defense", "maintaining control"],
    description: "The Seven of Wands represents perseverance, defense, and maintaining your position.",
    uprightMeaning: "Challenge, competition, protection, perseverance. Stand your ground.",
    reversedMeaning: "Exhaustion, giving up, overwhelmed. Feeling unable to defend your position.",
    loveMeaning: "Defending your relationship. Standing firm in what you believe about love.",
    careerMeaning: "Professional challenges requiring perseverance. Defending your position.",
    financeMeaning: "Protecting your financial position. Defending against financial threats.",
    healthMeaning: "Persevering through health challenges. Don't give up on wellness goals.",
  }),
  createMinorCard("wands", 8, "Eight of Wands", {
    keywords: ["speed", "action", "movement", "quick decisions"],
    description: "The Eight of Wands represents speed, action, and rapid movement forward.",
    uprightMeaning: "Movement, fast paced change, action, alignment, air travel. Things are moving quickly.",
    reversedMeaning: "Delays, frustration, resisting change, internal alignment needed.",
    loveMeaning: "Fast-moving romance. Quick developments in your love life.",
    careerMeaning: "Rapid career developments. Fast-paced professional changes.",
    financeMeaning: "Quick financial movements. Rapid changes in your monetary situation.",
    healthMeaning: "Rapid health improvements. Quick results from wellness efforts.",
  }),
  createMinorCard("wands", 9, "Nine of Wands", {
    keywords: ["resilience", "courage", "persistence", "last stand"],
    description: "The Nine of Wands represents resilience, courage, and persistence despite challenges.",
    uprightMeaning: "Resilience, grit, last stand, courage, persistence. You're almost there.",
    reversedMeaning: "Inner resources, struggle, overwhelm, giving up too soon.",
    loveMeaning: "Persevering in love despite challenges. Showing resilience in relationships.",
    careerMeaning: "Career resilience. Pushing through the final obstacles to success.",
    financeMeaning: "Financial perseverance. Almost at your financial goal, keep going.",
    healthMeaning: "Health resilience. Keep fighting through health challenges.",
  }),
  createMinorCard("wands", 10, "Ten of Wands", {
    keywords: ["burden", "responsibility", "hard work", "stress"],
    description: "The Ten of Wands represents burden, extra responsibility, and hard work.",
    uprightMeaning: "Burden, extra responsibility, hard work, completion. The weight is heavy but temporary.",
    reversedMeaning: "Doing it all, carrying burdens, delegation, release. Learning to let go.",
    loveMeaning: "Feeling burdened in love. Too much responsibility in your relationship.",
    careerMeaning: "Work overload and excessive responsibilities. Time to delegate.",
    financeMeaning: "Financial burden. Carrying too much monetary responsibility.",
    healthMeaning: "Stress and overwork affecting health. Time to lighten your load.",
  }),
  createMinorCard("wands", 11, "Page of Wands", {
    keywords: ["exploration", "excitement", "freedom", "discovery"],
    description: "The Page of Wands represents exploration, excitement, and a free spirit.",
    uprightMeaning: "Inspiration, ideas, discovery, limitless potential, free spirit.",
    reversedMeaning: "Newly forming ideas, redirecting energy, self-limiting beliefs.",
    loveMeaning: "Exciting new romantic possibilities. Youthful and passionate energy.",
    careerMeaning: "New career ideas and exciting professional possibilities.",
    financeMeaning: "New financial ideas and opportunities for growth.",
    healthMeaning: "New enthusiasm for health. Exciting wellness discoveries.",
  }),
  createMinorCard("wands", 12, "Knight of Wands", {
    keywords: ["energy", "passion", "adventure", "impulsiveness"],
    description: "The Knight of Wands represents energy, passion, and inspired action.",
    uprightMeaning: "Energy, passion, inspired action, adventure, impulsiveness.",
    reversedMeaning: "Passion project, haste, scattered energy, delays, frustration.",
    loveMeaning: "Passionate and adventurous romance. Impulsive love decisions.",
    careerMeaning: "Passionate career pursuit. Taking bold professional action.",
    financeMeaning: "Passionate financial pursuits. Bold but potentially risky money moves.",
    healthMeaning: "High energy and vitality. Channel passion into health goals.",
  }),
  createMinorCard("wands", 13, "Queen of Wands", {
    keywords: ["courage", "confidence", "independence", "warmth"],
    description: "The Queen of Wands represents courage, confidence, and determination.",
    uprightMeaning: "Courage, confidence, independence, social butterfly, determination.",
    reversedMeaning: "Self-respect, self-confidence rebuilding, introverted, re-establishing sense of self.",
    loveMeaning: "Confident and warm in love. Attracting partners with charisma.",
    careerMeaning: "Professional confidence and leadership. Inspiring others at work.",
    financeMeaning: "Confident financial management. Independent money decisions.",
    healthMeaning: "Confident and energetic health. Warmth and vitality.",
  }),
  createMinorCard("wands", 14, "King of Wands", {
    keywords: ["leadership", "vision", "entrepreneur", "honor"],
    description: "The King of Wands represents natural-born leadership, vision, and ambition.",
    uprightMeaning: "Natural-born leader, vision, entrepreneur, honor. Leading with passion.",
    reversedMeaning: "Impulsiveness, haste, ruthless, high expectations of others.",
    loveMeaning: "Passionate and visionary in love. Leading relationships with warmth.",
    careerMeaning: "Entrepreneurial leadership. Visionary professional direction.",
    financeMeaning: "Entrepreneurial financial leadership. Bold and visionary money moves.",
    healthMeaning: "Strong leadership in health. Taking charge of wellness with vision.",
  }),
];

// ============================================
// Minor Arcana - Cups
// ============================================

const cups: TarotCard[] = [
  createMinorCard("cups", 1, "Ace of Cups", {
    keywords: ["love", "new feelings", "emotional awakening", "creativity"],
    description: "The Ace of Cups represents new love, emotional awakening, and creative inspiration.",
    uprightMeaning: "Love, new relationships, compassion, creativity. An overflow of emotional gifts.",
    reversedMeaning: "Self-love, intuition blocked, repressed emotions. Emotional emptiness.",
    loveMeaning: "New love entering your life. Emotional overflow and deep connections.",
    careerMeaning: "Creative inspiration at work. Emotional fulfillment in career.",
    financeMeaning: "Emotional fulfillment around finances. Generosity and abundance.",
    healthMeaning: "Emotional healing and wellness. Heart-centered health approach.",
  }),
  createMinorCard("cups", 2, "Two of Cups", {
    keywords: ["partnership", "unity", "attraction", "connection"],
    description: "The Two of Cups represents unified love, partnership, and mutual attraction.",
    uprightMeaning: "Unified love, partnership, mutual attraction. A deep soul connection.",
    reversedMeaning: "Self-love, break-up, disharmony, distrust. Disconnection from others.",
    loveMeaning: "Deep romantic partnership. Soulmate connection and mutual love.",
    careerMeaning: "Productive partnerships at work. Mutual respect and collaboration.",
    financeMeaning: "Joint financial ventures. Partnership-based financial success.",
    healthMeaning: "Emotional balance through connection. Healing through relationships.",
  }),
  createMinorCard("cups", 3, "Three of Cups", {
    keywords: ["celebration", "friendship", "community", "joy"],
    description: "The Three of Cups represents celebration, friendship, and creative collaboration.",
    uprightMeaning: "Celebration, friendship, creativity, collaborations. Joyful social connections.",
    reversedMeaning: "Independence, alone time, hardcore partying, three's a crowd.",
    loveMeaning: "Celebrating love with friends and community. Joyful social events.",
    careerMeaning: "Team celebrations and collaborative success. Joyful work environment.",
    financeMeaning: "Financial celebrations with friends. Group financial success.",
    healthMeaning: "Social health and community wellness. Joy through connection.",
  }),
  createMinorCard("cups", 4, "Four of Cups", {
    keywords: ["meditation", "contemplation", "apathy", "reevaluation"],
    description: "The Four of Cups represents contemplation, meditation, and reevaluation.",
    uprightMeaning: "Meditation, contemplation, apathy, reevaluation. Taking time to reflect.",
    reversedMeaning: "Retreat, withdrawal, checking in for alignment. Renewed interest.",
    loveMeaning: "Feeling disconnected in love. Time for relationship contemplation.",
    careerMeaning: "Career apathy or contemplation. Reevaluating professional direction.",
    financeMeaning: "Financial contemplation. Not seeing opportunities right in front of you.",
    healthMeaning: "Mental health reflection. Time for emotional self-care.",
  }),
  createMinorCard("cups", 5, "Five of Cups", {
    keywords: ["loss", "grief", "disappointment", "pessimism"],
    description: "The Five of Cups represents loss, grief, and focusing on what's lost.",
    uprightMeaning: "Regret, failure, disappointment, pessimism. Focus on what remains, not what's lost.",
    reversedMeaning: "Personal setbacks, self-forgiveness, moving on. Finding acceptance.",
    loveMeaning: "Relationship loss or disappointment. Grieving but beginning to heal.",
    careerMeaning: "Professional disappointment. Learning from career setbacks.",
    financeMeaning: "Financial loss or regret. Focus on remaining resources.",
    healthMeaning: "Emotional grief affecting health. Allow yourself to grieve and heal.",
  }),
  createMinorCard("cups", 6, "Six of Cups", {
    keywords: ["nostalgia", "memories", "innocence", "joy"],
    description: "The Six of Cups represents nostalgia, memories, and reuniting with the past.",
    uprightMeaning: "Revisiting the past, childhood memories, innocence, joy. Sweet nostalgia.",
    reversedMeaning: "Living in the past, forgiveness, lacking playfulness.",
    loveMeaning: "Nostalgic love. Reconnecting with an ex or childhood sweetheart.",
    careerMeaning: "Returning to a former career or workplace. Past skills become relevant.",
    financeMeaning: "Financial nostalgia. Past financial patterns repeating.",
    healthMeaning: "Childhood health patterns. Addressing old health issues.",
  }),
  createMinorCard("cups", 7, "Seven of Cups", {
    keywords: ["choices", "fantasy", "illusion", "wishful thinking"],
    description: "The Seven of Cups represents opportunities, choices, and wishful thinking.",
    uprightMeaning: "Opportunities, choices, wishful thinking, illusion. So many options to consider.",
    reversedMeaning: "Alignment, personal values, overwhelming choices. Getting real.",
    loveMeaning: "Many romantic options. Be careful of unrealistic expectations in love.",
    careerMeaning: "Many career opportunities. Choose wisely among professional options.",
    financeMeaning: "Multiple financial opportunities. Avoid get-rich-quick fantasies.",
    healthMeaning: "Many health options. Choose realistic wellness approaches.",
  }),
  createMinorCard("cups", 8, "Eight of Cups", {
    keywords: ["walking away", "disillusionment", "leaving behind", "search for truth"],
    description: "The Eight of Cups represents walking away, seeking deeper meaning.",
    uprightMeaning: "Disappointment, abandonment, withdrawal, escapism. Walking away to seek more.",
    reversedMeaning: "Trying one more time, indecision, aimless drifting.",
    loveMeaning: "Walking away from unfulfilling love. Seeking deeper romantic connection.",
    careerMeaning: "Leaving an unfulfilling career. Seeking purpose in work.",
    financeMeaning: "Walking away from financial situations that don't serve you.",
    healthMeaning: "Abandoning health approaches that aren't working. Seeking better solutions.",
  }),
  createMinorCard("cups", 9, "Nine of Cups", {
    keywords: ["contentment", "satisfaction", "gratitude", "wish fulfillment"],
    description: "The Nine of Cups is the wish card, representing satisfaction and emotional fulfillment.",
    uprightMeaning: "Contentment, satisfaction, gratitude, wish come true. The wish card.",
    reversedMeaning: "Inner happiness, materialism, dissatisfaction, overindulgence.",
    loveMeaning: "Romantic wishes fulfilled. Deep emotional satisfaction in love.",
    careerMeaning: "Career wishes coming true. Professional satisfaction and contentment.",
    financeMeaning: "Financial wishes fulfilled. Material satisfaction and abundance.",
    healthMeaning: "Health wishes fulfilled. Emotional and physical satisfaction.",
  }),
  createMinorCard("cups", 10, "Ten of Cups", {
    keywords: ["divine love", "harmony", "alignment", "happy family"],
    description: "The Ten of Cups represents divine love, blissful relationships, and harmony.",
    uprightMeaning: "Divine love, blissful relationships, harmony, alignment. Ultimate emotional fulfillment.",
    reversedMeaning: "Disconnection, misaligned values, struggling to maintain harmony.",
    loveMeaning: "Ultimate romantic fulfillment. Happy family and blissful partnership.",
    careerMeaning: "Career harmony and fulfillment. Professional life aligned with values.",
    financeMeaning: "Financial harmony and family prosperity. All needs met.",
    healthMeaning: "Complete emotional wellness. Harmony in all aspects of health.",
  }),
  createMinorCard("cups", 11, "Page of Cups", {
    keywords: ["creative opportunities", "intuition", "curiosity", "possibility"],
    description: "The Page of Cups represents creative opportunities and intuitive messages.",
    uprightMeaning: "Creative opportunities, intuitive messages, curiosity, possibility.",
    reversedMeaning: "New ideas, doubting intuition, creative blocks, emotional immaturity.",
    loveMeaning: "New romantic message or proposal. Youthful love energy.",
    careerMeaning: "Creative career opportunities. Intuitive professional messages.",
    financeMeaning: "New financial opportunity driven by intuition.",
    healthMeaning: "Emotional health insights. Intuitive health messages.",
  }),
  createMinorCard("cups", 12, "Knight of Cups", {
    keywords: ["romance", "charm", "imagination", "beauty"],
    description: "The Knight of Cups represents romance, charm, and following the heart.",
    uprightMeaning: "Romance, charm, imagination, beauty, romantic proposals.",
    reversedMeaning: "Overactive imagination, unrealistic, jealousy, moodiness.",
    loveMeaning: "Romantic proposal or gesture. Following your heart in love.",
    careerMeaning: "Creative career pursuit. Following professional passion.",
    financeMeaning: "Following your heart in financial decisions. Creative investments.",
    healthMeaning: "Emotional approach to health. Following intuition for wellness.",
  }),
  createMinorCard("cups", 13, "Queen of Cups", {
    keywords: ["compassion", "calm", "comfort", "intuition"],
    description: "The Queen of Cups represents compassion, emotional security, and intuition.",
    uprightMeaning: "Compassionate, caring, emotionally stable, intuitive, in flow.",
    reversedMeaning: "Inner feelings, self-care, self-love, co-dependency.",
    loveMeaning: "Compassionate and nurturing love. Deep emotional connection.",
    careerMeaning: "Empathetic leadership. Caring professional approach.",
    financeMeaning: "Emotional intelligence in finances. Compassionate money management.",
    healthMeaning: "Emotional healing and self-care. Nurturing approach to health.",
  }),
  createMinorCard("cups", 14, "King of Cups", {
    keywords: ["emotional balance", "control", "generosity", "diplomacy"],
    description: "The King of Cups represents emotional balance and generosity.",
    uprightMeaning: "Emotionally balanced, compassionate, diplomatic. Mastering emotions.",
    reversedMeaning: "Self-compassion, inner feelings, moodiness, emotionally manipulative.",
    loveMeaning: "Emotionally balanced and mature love. Diplomatic in relationships.",
    careerMeaning: "Emotionally intelligent leadership. Diplomatic professional approach.",
    financeMeaning: "Balanced and generous financial approach. Emotional intelligence in money.",
    healthMeaning: "Emotional mastery and health. Balanced approach to wellness.",
  }),
];

// ============================================
// Minor Arcana - Swords
// ============================================

const swords: TarotCard[] = [
  createMinorCard("swords", 1, "Ace of Swords", {
    keywords: ["breakthrough", "clarity", "sharp mind", "truth"],
    description: "The Ace of Swords represents a breakthrough, clarity, and sharp mental power.",
    uprightMeaning: "Breakthrough, clarity, sharp mind, truth, new idea. Mental clarity cuts through confusion.",
    reversedMeaning: "Inner clarity, re-thinking an idea, clouded judgement.",
    loveMeaning: "Clarity in love. Honest communication and breakthrough conversations.",
    careerMeaning: "Professional breakthrough. New ideas and mental clarity at work.",
    financeMeaning: "Financial clarity. Clear thinking about money matters.",
    healthMeaning: "Mental clarity and health breakthroughs. Clear diagnosis.",
  }),
  createMinorCard("swords", 2, "Two of Swords", {
    keywords: ["difficult choices", "indecision", "stalemate", "avoidance"],
    description: "The Two of Swords represents difficult choices and a crossroads.",
    uprightMeaning: "Difficult choices, weighing options, an impasse, avoidance.",
    reversedMeaning: "Indecision, confusion, information overload, stalemate.",
    loveMeaning: "Relationship crossroads. Difficult love decisions ahead.",
    careerMeaning: "Career crossroads. Weighing professional options carefully.",
    financeMeaning: "Financial indecision. Weighing monetary options.",
    healthMeaning: "Health decisions needed. Weighing treatment options.",
  }),
  createMinorCard("swords", 3, "Three of Swords", {
    keywords: ["heartbreak", "emotional pain", "sorrow", "grief"],
    description: "The Three of Swords represents heartbreak, sorrow, and emotional pain.",
    uprightMeaning: "Heartbreak, emotional pain, sorrow, grief, hurt. A painful but necessary truth.",
    reversedMeaning: "Recovery, forgiveness, moving on, releasing pain.",
    loveMeaning: "Heartbreak in love. Painful relationship truths surfacing.",
    careerMeaning: "Professional disappointment and emotional pain at work.",
    financeMeaning: "Financial heartbreak. Painful monetary losses.",
    healthMeaning: "Emotional pain affecting physical health. Heart health awareness.",
  }),
  createMinorCard("swords", 4, "Four of Swords", {
    keywords: ["rest", "relaxation", "meditation", "recovery"],
    description: "The Four of Swords represents rest, recovery, and contemplation.",
    uprightMeaning: "Rest, relaxation, meditation, contemplation, recuperation.",
    reversedMeaning: "Exhaustion, burn-out, deep contemplation, stagnation.",
    loveMeaning: "Taking a break in love. Rest and recovery in relationships.",
    careerMeaning: "Professional rest and recovery. Taking a career break.",
    financeMeaning: "Financial rest. Pausing spending and recovering financially.",
    healthMeaning: "Rest and recovery essential. Take time to heal and rejuvenate.",
  }),
  createMinorCard("swords", 5, "Five of Swords", {
    keywords: ["conflict", "defeat", "winning at all costs", "hostility"],
    description: "The Five of Swords represents conflict, defeat, and hollow victories.",
    uprightMeaning: "Conflict, disagreements, competition, defeat, winning at all costs.",
    reversedMeaning: "Reconciliation, forgiveness, past resentment, making amends.",
    loveMeaning: "Relationship conflicts and power struggles. Choose your battles wisely.",
    careerMeaning: "Workplace conflicts and competition. Avoid winning at others' expense.",
    financeMeaning: "Financial conflicts and disputes. Hollow monetary victories.",
    healthMeaning: "Stress from conflicts affecting health. Choose peace.",
  }),
  createMinorCard("swords", 6, "Six of Swords", {
    keywords: ["transition", "leaving behind", "moving on", "healing"],
    description: "The Six of Swords represents transition, moving on, and leaving the past behind.",
    uprightMeaning: "Transition, change, rite of passage, releasing baggage.",
    reversedMeaning: "Personal transition, resistance to change, unfinished business.",
    loveMeaning: "Moving on from past love. Transitioning to better romantic times.",
    careerMeaning: "Career transition. Moving to better professional opportunities.",
    financeMeaning: "Financial transition. Moving away from monetary difficulties.",
    healthMeaning: "Health transition. Moving toward better wellness.",
  }),
  createMinorCard("swords", 7, "Seven of Swords", {
    keywords: ["deception", "trickery", "strategy", "resourcefulness"],
    description: "The Seven of Swords represents strategy, deception, and getting away with something.",
    uprightMeaning: "Betrayal, deception, getting away with it, acting strategically.",
    reversedMeaning: "Imposter syndrome, self-deceit, keeping secrets.",
    loveMeaning: "Deception in love. Trust issues in relationships.",
    careerMeaning: "Professional deception or strategic career moves.",
    financeMeaning: "Financial deception. Be wary of dishonest money dealings.",
    healthMeaning: "Self-deception about health. Face health truths honestly.",
  }),
  createMinorCard("swords", 8, "Eight of Swords", {
    keywords: ["imprisonment", "self-limiting beliefs", "victim mentality", "isolation"],
    description: "The Eight of Swords represents feeling trapped by your own thoughts.",
    uprightMeaning: "Negative thoughts, self-imposed restriction, imprisonment, victim mentality.",
    reversedMeaning: "Self-acceptance, new perspective, freedom from limitations.",
    loveMeaning: "Feeling trapped in love. Self-imposed romantic limitations.",
    careerMeaning: "Feeling stuck in your career. Self-limiting professional beliefs.",
    financeMeaning: "Feeling financially trapped. Breaking free from money fears.",
    healthMeaning: "Mental health: feeling imprisoned by anxiety or fear.",
  }),
  createMinorCard("swords", 9, "Nine of Swords", {
    keywords: ["anxiety", "worry", "fear", "depression"],
    description: "The Nine of Swords represents anxiety, worry, and nightmares.",
    uprightMeaning: "Anxiety, worry, fear, depression, nightmares. The mind creates suffering.",
    reversedMeaning: "Inner turmoil, deep-seated fears, secrets, releasing worry.",
    loveMeaning: "Anxiety about love. Worrying excessively about relationships.",
    careerMeaning: "Work anxiety and professional fears. Excessive worry about career.",
    financeMeaning: "Financial anxiety and money worries keeping you up at night.",
    healthMeaning: "Anxiety affecting health. Insomnia, stress, and mental health concerns.",
  }),
  createMinorCard("swords", 10, "Ten of Swords", {
    keywords: ["painful endings", "deep wounds", "betrayal", "rock bottom"],
    description: "The Ten of Swords represents painful endings and hitting rock bottom.",
    uprightMeaning: "Painful endings, deep wounds, betrayal, loss, crisis. It can only go up from here.",
    reversedMeaning: "Recovery, regeneration, resisting an inevitable end.",
    loveMeaning: "Painful end to a relationship. Rock bottom leading to new love.",
    careerMeaning: "Career ending or professional betrayal. New beginnings from the ashes.",
    financeMeaning: "Financial rock bottom. The worst is over, recovery begins.",
    healthMeaning: "Health crisis reaching its peak. Recovery begins now.",
  }),
  createMinorCard("swords", 11, "Page of Swords", {
    keywords: ["curiosity", "new ideas", "thirst for knowledge", "communication"],
    description: "The Page of Swords represents curiosity, new ideas, and communication.",
    uprightMeaning: "New ideas, curiosity, thirst for knowledge, new ways of communicating.",
    reversedMeaning: "Self-expression, all talk and no action, haphazard action.",
    loveMeaning: "Curious and communicative in love. New ideas about relationships.",
    careerMeaning: "Intellectual curiosity at work. New professional ideas.",
    financeMeaning: "New financial ideas and learning about money management.",
    healthMeaning: "Researching health options. Curiosity about new wellness approaches.",
  }),
  createMinorCard("swords", 12, "Knight of Swords", {
    keywords: ["ambitious", "action-oriented", "driven", "fast thinking"],
    description: "The Knight of Swords charges forward with ambition and determination.",
    uprightMeaning: "Ambitious, action-oriented, driven to succeed, fast thinking.",
    reversedMeaning: "Restless, unfocused, impulsive, burn-out from rushing.",
    loveMeaning: "Charging into love with determination. Fast-moving romance.",
    careerMeaning: "Ambitious career moves. Driven professional pursuit.",
    financeMeaning: "Fast financial decisions. Ambitious money moves.",
    healthMeaning: "Fast-paced approach to health. Don't rush the healing process.",
  }),
  createMinorCard("swords", 13, "Queen of Swords", {
    keywords: ["independent", "unbiased", "clear communication", "direct"],
    description: "The Queen of Swords represents clear, independent thinking and honest communication.",
    uprightMeaning: "Independent, unbiased judgement, clear boundaries, direct communication.",
    reversedMeaning: "Overly emotional, easily influenced, bitchy, cold-hearted.",
    loveMeaning: "Independent and honest in love. Clear romantic boundaries.",
    careerMeaning: "Professional independence and clear communication at work.",
    financeMeaning: "Independent financial thinking. Clear boundaries with money.",
    healthMeaning: "Clear-headed approach to health decisions. Direct communication with doctors.",
  }),
  createMinorCard("swords", 14, "King of Swords", {
    keywords: ["mental clarity", "intellectual power", "authority", "truth"],
    description: "The King of Swords represents intellectual power, clear thinking, and authority.",
    uprightMeaning: "Mental clarity, intellectual power, authority, truth.",
    reversedMeaning: "Quiet power, inner truth, misuse of power, manipulation.",
    loveMeaning: "Intellectual connection in love. Clear and honest communication.",
    careerMeaning: "Intellectual authority at work. Leading with clarity and truth.",
    financeMeaning: "Clear financial thinking and intellectual money management.",
    healthMeaning: "Mental clarity in health. Intellectual approach to wellness.",
  }),
];

// ============================================
// Minor Arcana - Pentacles
// ============================================

const pentacles: TarotCard[] = [
  createMinorCard("pentacles", 1, "Ace of Pentacles", {
    keywords: ["new financial opportunity", "prosperity", "abundance", "security"],
    description: "The Ace of Pentacles represents new financial or material opportunities.",
    uprightMeaning: "A new financial or career opportunity, manifestation, abundance.",
    reversedMeaning: "Lost opportunity, lack of planning, missed chance for prosperity.",
    loveMeaning: "Stable new love with long-term potential. Material security in romance.",
    careerMeaning: "New career opportunity with financial growth potential.",
    financeMeaning: "New financial opportunity. Abundance and prosperity incoming.",
    healthMeaning: "New health beginning. Physical vitality and grounded wellness.",
  }),
  createMinorCard("pentacles", 2, "Two of Pentacles", {
    keywords: ["balance", "adaptability", "time management", "prioritization"],
    description: "The Two of Pentacles represents balancing multiple priorities.",
    uprightMeaning: "Multiple priorities, time management, prioritization, adaptability.",
    reversedMeaning: "Over-committed, disorganized, reprioritization needed.",
    loveMeaning: "Balancing love with other priorities. Time management in relationships.",
    careerMeaning: "Juggling multiple professional responsibilities. Work-life balance.",
    financeMeaning: "Balancing finances. Managing multiple monetary responsibilities.",
    healthMeaning: "Balancing health with busy schedule. Adaptable wellness approach.",
  }),
  createMinorCard("pentacles", 3, "Three of Pentacles", {
    keywords: ["teamwork", "collaboration", "learning", "implementation"],
    description: "The Three of Pentacles represents teamwork, collaboration, and skilled work.",
    uprightMeaning: "Teamwork, collaboration, learning, implementation. Building something together.",
    reversedMeaning: "Disharmony, lack of teamwork, working alone, low motivation.",
    loveMeaning: "Building a relationship together. Collaborative love efforts.",
    careerMeaning: "Professional teamwork and collaboration. Building career foundations.",
    financeMeaning: "Collaborative financial efforts. Team-based financial success.",
    healthMeaning: "Team approach to health. Working with professionals for wellness.",
  }),
  createMinorCard("pentacles", 4, "Four of Pentacles", {
    keywords: ["conservation", "security", "frugality", "control"],
    description: "The Four of Pentacles represents financial security and conservation.",
    uprightMeaning: "Conservation, frugality, security, savings, materialism, control.",
    reversedMeaning: "Over-spending, greed, self-protection, hoarding.",
    loveMeaning: "Holding on too tightly in love. Fear of losing your partner.",
    careerMeaning: "Job security focus. Conservative professional approach.",
    financeMeaning: "Financial security and savings. Conservative money management.",
    healthMeaning: "Physical security and stability. Grounded health approach.",
  }),
  createMinorCard("pentacles", 5, "Five of Pentacles", {
    keywords: ["financial loss", "poverty", "lack mentality", "isolation"],
    description: "The Five of Pentacles represents financial hardship and insecurity.",
    uprightMeaning: "Financial loss, poverty, lack mindset, isolation, worry.",
    reversedMeaning: "Recovery from financial loss, spiritual poverty, finding help.",
    loveMeaning: "Feeling emotionally impoverished. Financial stress affecting love.",
    careerMeaning: "Job loss or career hardship. Professional insecurity.",
    financeMeaning: "Financial hardship and losses. Seek help and support.",
    healthMeaning: "Health challenges and feeling unsupported. Seek help.",
  }),
  createMinorCard("pentacles", 6, "Six of Pentacles", {
    keywords: ["generosity", "charity", "giving", "receiving"],
    description: "The Six of Pentacles represents generosity, sharing, and balance in giving and receiving.",
    uprightMeaning: "Giving, receiving, sharing wealth, generosity, charity.",
    reversedMeaning: "Self-care, unpaid debts, one-sided charity.",
    loveMeaning: "Generous love. Balanced giving and receiving in relationships.",
    careerMeaning: "Professional generosity. Sharing knowledge and resources.",
    financeMeaning: "Generous with finances. Charitable giving and receiving help.",
    healthMeaning: "Generous health. Sharing wellness knowledge and receiving care.",
  }),
  createMinorCard("pentacles", 7, "Seven of Pentacles", {
    keywords: ["patience", "long-term view", "perseverance", "investment"],
    description: "The Seven of Pentacles represents long-term investment and patient effort.",
    uprightMeaning: "Long-term view, sustainable results, perseverance, investment.",
    reversedMeaning: "Lack of long-term vision, limited success, impatience.",
    loveMeaning: "Patient investment in love. Long-term relationship building.",
    careerMeaning: "Long-term career investment. Patient professional development.",
    financeMeaning: "Long-term financial investment. Patient wealth building.",
    healthMeaning: "Patient health investment. Long-term wellness approach.",
  }),
  createMinorCard("pentacles", 8, "Eight of Pentacles", {
    keywords: ["apprenticeship", "skill development", "diligence", "mastery"],
    description: "The Eight of Pentacles represents dedication, skill development, and mastery.",
    uprightMeaning: "Apprenticeship, repetitive tasks, mastery, skill development.",
    reversedMeaning: "Self-development, perfectionism, misdirected activity.",
    loveMeaning: "Working on relationship skills. Dedicated effort in love.",
    careerMeaning: "Skill mastery and professional development. Dedicated work.",
    financeMeaning: "Financial skill development. Diligent money management learning.",
    healthMeaning: "Dedicated health improvement. Mastering wellness habits.",
  }),
  createMinorCard("pentacles", 9, "Nine of Pentacles", {
    keywords: ["abundance", "luxury", "self-sufficiency", "financial independence"],
    description: "The Nine of Pentacles represents financial independence, luxury, and self-sufficiency.",
    uprightMeaning: "Abundance, luxury, self-sufficiency, financial independence.",
    reversedMeaning: "Self-worth, over-investment in work, hustling, superficial luxury.",
    loveMeaning: "Independent in love. Self-sufficient and confident in relationships.",
    careerMeaning: "Professional success and self-sufficiency. Enjoying the fruits of labor.",
    financeMeaning: "Financial independence and luxury. Self-made prosperity.",
    healthMeaning: "Luxurious self-care. Enjoying the rewards of healthy living.",
  }),
  createMinorCard("pentacles", 10, "Ten of Pentacles", {
    keywords: ["wealth", "inheritance", "family", "establishment"],
    description: "The Ten of Pentacles represents long-term success, family wealth, and legacy.",
    uprightMeaning: "Wealth, financial security, family, long-term success, contribution.",
    reversedMeaning: "The dark side of wealth, financial failure, loneliness.",
    loveMeaning: "Family love and long-term commitment. Building a legacy together.",
    careerMeaning: "Long-term career success and establishment. Legacy building.",
    financeMeaning: "Family wealth and financial legacy. Long-term prosperity.",
    healthMeaning: "Family health and genetic awareness. Long-term wellness legacy.",
  }),
  createMinorCard("pentacles", 11, "Page of Pentacles", {
    keywords: ["manifestation", "financial opportunity", "skill development", "ambition"],
    description: "The Page of Pentacles represents ambition, desire for knowledge, and new career paths.",
    uprightMeaning: "Manifestation, financial opportunity, skill development.",
    reversedMeaning: "Lack of progress, procrastination, learning from failure.",
    loveMeaning: "Practical approach to new love. Building stable romantic foundations.",
    careerMeaning: "New career learning opportunity. Ambitious professional beginnings.",
    financeMeaning: "New financial opportunity for learning and growth.",
    healthMeaning: "Learning about health. New practical wellness approach.",
  }),
  createMinorCard("pentacles", 12, "Knight of Pentacles", {
    keywords: ["hard work", "productivity", "routine", "conservatism"],
    description: "The Knight of Pentacles represents hard work, routine, and methodical progress.",
    uprightMeaning: "Hard work, productivity, routine, conservatism.",
    reversedMeaning: "Self-discipline, boredom, feeling stuck, perfectionism.",
    loveMeaning: "Steady and reliable love. Methodical approach to romance.",
    careerMeaning: "Hard-working professional. Steady career progress through effort.",
    financeMeaning: "Methodical financial approach. Steady wealth building.",
    healthMeaning: "Consistent health routine. Disciplined wellness approach.",
  }),
  createMinorCard("pentacles", 13, "Queen of Pentacles", {
    keywords: ["nurturing", "practical", "financial security", "homebody"],
    description: "The Queen of Pentacles represents practical nurturing and financial security.",
    uprightMeaning: "Practicality, creature comforts, financial security, nurturing.",
    reversedMeaning: "Self-care, work-home conflict, financial insecurity.",
    loveMeaning: "Nurturing and practical love. Creating a comfortable home life.",
    careerMeaning: "Practical professional approach. Nurturing work environment.",
    financeMeaning: "Financial security and practical money management.",
    healthMeaning: "Nurturing self-care. Practical and grounded health approach.",
  }),
  createMinorCard("pentacles", 14, "King of Pentacles", {
    keywords: ["wealth", "business", "leadership", "security"],
    description: "The King of Pentacles represents wealth, business acumen, and material abundance.",
    uprightMeaning: "Wealth, business, leadership, security, discipline, abundance.",
    reversedMeaning: "Financially inept, obsessed with wealth, stubborn.",
    loveMeaning: "Secure and stable love. Providing for your partner generously.",
    careerMeaning: "Business leadership and financial success. Top of your profession.",
    financeMeaning: "Ultimate financial success and wealth. Masterful money management.",
    healthMeaning: "Investing in premium health. Financial ability to afford best care.",
  }),
];

// ============================================
// Complete Deck Export
// ============================================

export const tarotDeck: TarotCard[] = [
  ...majorArcana,
  ...wands,
  ...cups,
  ...swords,
  ...pentacles,
];

export default tarotDeck;
